export const ASSET_TYPE_LABELS = {
  laptop: 'Laptop',
  escritorio: 'Escritorio',
  all_in_one: 'All-in-One',
  monitor: 'Monitor',
  mouse: 'Mouse',
  teclado: 'Teclado',
  cargador_laptop: 'Cargador Laptop',
  celular: 'Celular',
  tablet: 'Tablet',
  cargador_celular: 'Cargador Celular',
  cable: 'Cable',
  consumible: 'Consumible',
  kit_perifericos: 'Kit Teclado+Mouse',
  audifonos: 'Audífonos',
  impresora: 'Impresora',
  escaner: 'Escáner',
  herramienta: 'Herramienta',
  webcam: 'Webcam',
  hub_usb: 'Hub USB',
  accesorio: 'Accesorio',
  otro: 'Otro',
};

export const ACCESSORY_TYPE_LABELS = {
  tablet: 'Tablet',
  monitor: 'Monitor',
  mouse: 'Mouse',
  teclado: 'Teclado',
  kit_perifericos: 'Kit Teclado+Mouse',
  audifonos: 'Audífonos',
  webcam: 'Webcam',
  hub_usb: 'Hub USB',
  impresora: 'Impresora',
  escaner: 'Escáner',
  cable: 'Cable',
  consumible: 'Consumible',
  herramienta: 'Herramienta',
  accesorio: 'Accesorio',
};

export const ACCESSORY_GROUPS = [
  { label: 'Tablets',      icon: '📱', types: ['tablet'] },
  { label: 'Periféricos',  icon: '🖥️', types: ['monitor', 'mouse', 'teclado', 'kit_perifericos', 'audifonos', 'webcam', 'hub_usb'] },
  { label: 'Impresión',    icon: '🖨️', types: ['impresora', 'escaner'] },
  { label: 'Cables',       icon: '🔌', types: ['cable'] },
  { label: 'Consumibles',  icon: '🧹', types: ['consumible'] },
  { label: 'Herramientas', icon: '🔧', types: ['herramienta'] },
  { label: 'Otros',        icon: '📦', types: ['accesorio'] },
];

export const ASSET_GROUPS = [
  {
    label: 'Equipo de cómputo',
    icon: '💻',
    types: ['laptop', 'escritorio', 'all_in_one'],
  },
  {
    label: 'Periféricos',
    icon: '🖥️',
    types: ['monitor', 'mouse', 'teclado', 'cargador_laptop'],
  },
  {
    label: 'Móviles',
    icon: '📱',
    types: ['celular', 'tablet', 'cargador_celular'],
  },
  {
    label: 'Otros',
    icon: '📦',
    types: ['accesorio', 'otro'],
  },
];

export const SPECS_FIELDS = {
  laptop: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i7-1255U', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '16 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '512 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11 Pro', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'chargerSerial', label: 'No. serie del cargador', type: 'text', placeholder: 'SN-CARG-001', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'hasMonitor', label: 'Incluye monitor', type: 'boolean', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  escritorio: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i5-12400', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '8 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '1 TB HDD + 256 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11 Pro', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'psuSerial', label: 'No. serie fuente de alimentación', type: 'text', placeholder: 'SN-PSU-001', col: 1 },
    { key: 'hasMonitor', label: 'Incluye monitor', type: 'boolean', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  all_in_one: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i5-1235U', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '8 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '512 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11', col: 1 },
    { key: 'screenSize', label: 'Tamaño de pantalla', type: 'text', placeholder: '27"', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Blanco', col: 1 },
    { key: 'psuSerial', label: 'No. serie fuente de alimentación', type: 'text', placeholder: 'SN-PSU-001', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  monitor: [
    { key: 'screenSize', label: 'Tamaño (pulgadas)', type: 'text', placeholder: '24"', col: 1 },
    { key: 'resolution', label: 'Resolución', type: 'text', placeholder: '1920x1080 Full HD', col: 1 },
    { key: 'panelType', label: 'Tipo de panel', type: 'select', options: ['IPS', 'VA', 'TN', 'OLED', 'Otro'], col: 1 },
    { key: 'refreshRate', label: 'Frecuencia (Hz)', type: 'text', placeholder: '60Hz', col: 1 },
    { key: 'connectionType', label: 'Conexiones disponibles', type: 'text', placeholder: 'HDMI, DisplayPort, VGA', col: 2 },
  ],
  mouse: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['Alámbrico USB', 'Inalámbrico USB', 'Bluetooth', 'Dual'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  teclado: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['Alámbrico USB', 'Inalámbrico USB', 'Bluetooth', 'Dual'], col: 1 },
    { key: 'layout', label: 'Distribución', type: 'select', options: ['Español (LATAM)', 'Español (España)', 'Inglés (US)', 'Otro'], col: 1 },
    { key: 'keyType', label: 'Tipo de teclas', type: 'select', options: ['Membrana', 'Mecánico', 'Tijera', 'Otro'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  cargador_laptop: [
    { key: 'watts', label: 'Potencia (Watts)', type: 'text', placeholder: '65W', col: 1 },
    { key: 'connectorType', label: 'Tipo de conector', type: 'text', placeholder: 'USB-C / Barrel 4.5mm', col: 1 },
    { key: 'compatibleBrand', label: 'Marca compatible', type: 'text', placeholder: 'Dell', col: 1 },
    { key: 'compatibleModel', label: 'Modelo compatible', type: 'text', placeholder: 'Latitude 5540', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  celular: [
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'businessName', label: 'Razón social', type: 'text', placeholder: 'Empresa S.A. de C.V.', col: 1 },
    { key: 'gmailAccount', label: 'Correo Gmail', type: 'text', placeholder: 'usuario@gmail.com', col: 2 },
    { key: 'imei', label: 'IMEI 1', type: 'text', placeholder: '123456789012345', col: 1 },
    { key: 'imei2', label: 'IMEI 2 (Dual SIM)', type: 'text', placeholder: 'Opcional', col: 1 },
    { key: 'lineNumber', label: 'Número de línea', type: 'text', placeholder: '55 1234 5678', col: 1 },
    { key: 'carrier', label: 'Operadora', type: 'text', placeholder: 'Telcel / AT&T / Movistar', col: 1 },
    { key: 'planCost', label: 'Costo del plan', type: 'text', placeholder: '$299/mes', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '128 GB', col: 1 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '6 GB', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'select', options: ['Android', 'iOS'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'simLock', label: 'SIM bloqueada', type: 'boolean', col: 1 },
  ],
  tablet: [
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'businessName', label: 'Razón social', type: 'text', placeholder: 'Empresa S.A. de C.V.', col: 1 },
    { key: 'gmailAccount', label: 'Correo Gmail', type: 'text', placeholder: 'usuario@gmail.com', col: 2 },
    { key: 'imei', label: 'IMEI', type: 'text', placeholder: 'Si aplica (con SIM)', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '64 GB', col: 1 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '4 GB', col: 1 },
    { key: 'screenSize', label: 'Tamaño de pantalla', type: 'text', placeholder: '10.9"', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'select', options: ['Android', 'iPadOS', 'Windows'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Gris espacial', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado/funda', type: 'boolean', col: 1 },
  ],
  cargador_celular: [
    { key: 'watts', label: 'Potencia (Watts)', type: 'text', placeholder: '20W', col: 1 },
    { key: 'connectorType', label: 'Tipo de conector', type: 'select', options: ['USB-C', 'Lightning', 'Micro-USB', 'USB-A'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Blanco', col: 1 },
    { key: 'compatibleBrand', label: 'Marca compatible', type: 'text', placeholder: 'Apple / Samsung / Universal', col: 1 },
  ],
  cable: [
    { key: 'cableType', label: 'Tipo de cable', type: 'select', options: ['HDMI', 'DisplayPort', 'VGA', 'USB-A a USB-B', 'USB-A a USB-C', 'USB-C a USB-C', 'Red (RJ45)', 'Extensión eléctrica', 'Poder (PC)', 'Otro'], col: 2 },
    { key: 'length', label: 'Longitud', type: 'text', placeholder: '1.5 m', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  consumible: [
    { key: 'consumibleType', label: 'Tipo', type: 'select', options: ['Toalla limpiadora', 'Limpiador de pantalla', 'Gel antibacterial', 'Alcohol isopropílico', 'Aire comprimido', 'Otro'], col: 2 },
    { key: 'description', label: 'Descripción', type: 'text', placeholder: 'Observaciones...', col: 2 },
  ],
  kit_perifericos: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['Alámbrico USB', 'Inalámbrico USB', 'Bluetooth', 'Dual'], col: 1 },
    { key: 'layout', label: 'Distribución teclado', type: 'select', options: ['Español (LATAM)', 'Español (España)', 'Inglés (US)', 'Otro'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  audifonos: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['USB', 'Bluetooth', '3.5mm', 'USB-C', 'Dual'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'hasMic', label: 'Incluye micrófono', type: 'boolean', col: 1 },
  ],
  impresora: [
    { key: 'printerType', label: 'Tipo', type: 'select', options: ['Láser', 'Tinta', 'Multifuncional Láser', 'Multifuncional Tinta', 'Térmica', 'Otro'], col: 1 },
    { key: 'colorSupport', label: 'Color', type: 'select', options: ['Color', 'Blanco y negro'], col: 1 },
    { key: 'connectivity', label: 'Conectividad', type: 'select', options: ['USB', 'WiFi', 'Ethernet', 'USB + WiFi', 'USB + Ethernet', 'WiFi + Ethernet'], col: 1 },
    { key: 'ppm', label: 'Velocidad (ppm)', type: 'text', placeholder: '30 ppm', col: 1 },
    { key: 'ipAddress', label: 'IP de red', type: 'text', placeholder: '192.168.1.100', col: 1 },
    { key: 'color', label: 'Color del equipo', type: 'text', placeholder: 'Blanco', col: 1 },
  ],
  escaner: [
    { key: 'scannerType', label: 'Tipo', type: 'select', options: ['Cama plana', 'Alimentador ADF', 'Portátil', 'Multifuncional'], col: 1 },
    { key: 'resolution', label: 'Resolución', type: 'text', placeholder: '600 dpi', col: 1 },
    { key: 'connectivity', label: 'Conectividad', type: 'select', options: ['USB', 'WiFi', 'Ethernet'], col: 1 },
    { key: 'color', label: 'Color del equipo', type: 'text', placeholder: 'Blanco', col: 1 },
  ],
  herramienta: [
    { key: 'toolType', label: 'Tipo de herramienta', type: 'text', placeholder: 'Desarmadores / Pinzas / Pulsera antiestática...', col: 2 },
    { key: 'description', label: 'Descripción', type: 'text', placeholder: 'Detalles del set o herramienta individual', col: 2 },
  ],
  webcam: [
    { key: 'resolution', label: 'Resolución', type: 'select', options: ['720p', '1080p', '2K', '4K'], col: 1 },
    { key: 'connectionType', label: 'Conexión', type: 'select', options: ['USB-A', 'USB-C', 'Bluetooth'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'hasMic', label: 'Incluye micrófono', type: 'boolean', col: 1 },
  ],
  hub_usb: [
    { key: 'ports', label: 'Número de puertos', type: 'text', placeholder: '7', col: 1 },
    { key: 'usbVersion', label: 'Versión USB', type: 'select', options: ['USB 2.0', 'USB 3.0', 'USB 3.1', 'USB-C'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'hasPower', label: 'Con alimentación propia', type: 'boolean', col: 1 },
  ],
  accesorio: [
    { key: 'accessoryType', label: 'Tipo de accesorio', type: 'text', placeholder: 'Dock / Adaptador / Mochila...', col: 2 },
    { key: 'connectionType', label: 'Tipo de conexión', type: 'text', placeholder: 'USB / Bluetooth / 3.5mm', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'description', label: 'Descripción adicional', type: 'text', placeholder: 'Detalles relevantes', col: 2 },
  ],
  otro: [
    { key: 'description', label: 'Descripción', type: 'text', placeholder: 'Describir el activo', col: 2 },
    { key: 'category', label: 'Categoría', type: 'text', placeholder: 'Mueble / Herramienta / etc.', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
};

export const STATUS_CONFIG = {
  disponible: { label: 'Disponible', color: '#16a34a', bg: '#f0fdf4' },
  asignado: { label: 'Asignado', color: '#d97706', bg: '#fffbeb' },
  baja: { label: 'De baja', color: '#dc2626', bg: '#fef2f2' },
};

export const TYPE_ICONS = {
  laptop: '💻', escritorio: '🖥️', all_in_one: '🖥️',
  monitor: '🖥️', mouse: '🖱️', teclado: '⌨️', cargador_laptop: '🔌',
  celular: '📱', tablet: '📱', cargador_celular: '🔌',
  cable: '🔌', consumible: '🧹', kit_perifericos: '⌨️', audifonos: '🎧',
  impresora: '🖨️', escaner: '📠', herramienta: '🔧', webcam: '📷', hub_usb: '🔌',
  accesorio: '🎧', otro: '📦',
};
