export const ASSET_TYPE_LABELS = {
  laptop: 'Laptop',
  escritorio: 'Escritorio',
  all_in_one: 'All-in-One',
  monitor: 'Monitor',
  mouse: 'Mouse',
  teclado: 'Teclado',
  cargador_laptop: 'Cargador Laptop',
  celular: 'Celular',
  tablet: 'Tablet',
  cargador_celular: 'Cargador Celular',
  accesorio: 'Accesorio',
  otro: 'Otro',
};

export const ASSET_GROUPS = [
  {
    label: 'Equipo de cómputo',
    icon: '💻',
    types: ['laptop', 'escritorio', 'all_in_one'],
  },
  {
    label: 'Periféricos',
    icon: '🖥️',
    types: ['monitor', 'mouse', 'teclado', 'cargador_laptop'],
  },
  {
    label: 'Móviles',
    icon: '📱',
    types: ['celular', 'tablet', 'cargador_celular'],
  },
  {
    label: 'Otros',
    icon: '📦',
    types: ['accesorio', 'otro'],
  },
];

export const SPECS_FIELDS = {
  laptop: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i7-1255U', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '16 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '512 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11 Pro', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'chargerSerial', label: 'No. serie del cargador', type: 'text', placeholder: 'SN-CARG-001', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'hasMonitor', label: 'Incluye monitor', type: 'boolean', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  escritorio: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i5-12400', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '8 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '1 TB HDD + 256 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11 Pro', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'psuSerial', label: 'No. serie fuente de alimentación', type: 'text', placeholder: 'SN-PSU-001', col: 1 },
    { key: 'hasMonitor', label: 'Incluye monitor', type: 'boolean', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  all_in_one: [
    { key: 'ownership', label: 'Propiedad', type: 'select', options: ['Propia', 'Arrendamiento'], col: 1 },
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'anydesk', label: 'AnyDesk ID', type: 'text', placeholder: '123 456 789', col: 1 },
    { key: 'processor', label: 'Procesador', type: 'text', placeholder: 'Intel Core i5-1235U', col: 2 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '8 GB DDR4', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '512 GB SSD', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'text', placeholder: 'Windows 11', col: 1 },
    { key: 'screenSize', label: 'Tamaño de pantalla', type: 'text', placeholder: '27"', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Blanco', col: 1 },
    { key: 'psuSerial', label: 'No. serie fuente de alimentación', type: 'text', placeholder: 'SN-PSU-001', col: 1 },
    { key: 'hasMouse', label: 'Incluye mouse', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado', type: 'boolean', col: 1 },
  ],
  monitor: [
    { key: 'screenSize', label: 'Tamaño (pulgadas)', type: 'text', placeholder: '24"', col: 1 },
    { key: 'resolution', label: 'Resolución', type: 'text', placeholder: '1920x1080 Full HD', col: 1 },
    { key: 'panelType', label: 'Tipo de panel', type: 'select', options: ['IPS', 'VA', 'TN', 'OLED', 'Otro'], col: 1 },
    { key: 'refreshRate', label: 'Frecuencia (Hz)', type: 'text', placeholder: '60Hz', col: 1 },
    { key: 'connectionType', label: 'Conexiones disponibles', type: 'text', placeholder: 'HDMI, DisplayPort, VGA', col: 2 },
  ],
  mouse: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['Alámbrico USB', 'Inalámbrico USB', 'Bluetooth', 'Dual'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  teclado: [
    { key: 'connectionType', label: 'Tipo de conexión', type: 'select', options: ['Alámbrico USB', 'Inalámbrico USB', 'Bluetooth', 'Dual'], col: 1 },
    { key: 'layout', label: 'Distribución', type: 'select', options: ['Español (LATAM)', 'Español (España)', 'Inglés (US)', 'Otro'], col: 1 },
    { key: 'keyType', label: 'Tipo de teclas', type: 'select', options: ['Membrana', 'Mecánico', 'Tijera', 'Otro'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  cargador_laptop: [
    { key: 'watts', label: 'Potencia (Watts)', type: 'text', placeholder: '65W', col: 1 },
    { key: 'connectorType', label: 'Tipo de conector', type: 'text', placeholder: 'USB-C / Barrel 4.5mm', col: 1 },
    { key: 'compatibleBrand', label: 'Marca compatible', type: 'text', placeholder: 'Dell', col: 1 },
    { key: 'compatibleModel', label: 'Modelo compatible', type: 'text', placeholder: 'Latitude 5540', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
  celular: [
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'businessName', label: 'Razón social', type: 'text', placeholder: 'Empresa S.A. de C.V.', col: 1 },
    { key: 'gmailAccount', label: 'Correo Gmail', type: 'text', placeholder: 'usuario@gmail.com', col: 2 },
    { key: 'imei', label: 'IMEI 1', type: 'text', placeholder: '123456789012345', col: 1 },
    { key: 'imei2', label: 'IMEI 2 (Dual SIM)', type: 'text', placeholder: 'Opcional', col: 1 },
    { key: 'lineNumber', label: 'Número de línea', type: 'text', placeholder: '55 1234 5678', col: 1 },
    { key: 'carrier', label: 'Operadora', type: 'text', placeholder: 'Telcel / AT&T / Movistar', col: 1 },
    { key: 'planCost', label: 'Costo del plan', type: 'text', placeholder: '$299/mes', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '128 GB', col: 1 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '6 GB', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'select', options: ['Android', 'iOS'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'simLock', label: 'SIM bloqueada', type: 'boolean', col: 1 },
  ],
  tablet: [
    { key: 'contractNumber', label: 'Número de contrato', type: 'text', placeholder: 'CONT-2024-001', col: 1 },
    { key: 'businessName', label: 'Razón social', type: 'text', placeholder: 'Empresa S.A. de C.V.', col: 1 },
    { key: 'gmailAccount', label: 'Correo Gmail', type: 'text', placeholder: 'usuario@gmail.com', col: 2 },
    { key: 'imei', label: 'IMEI', type: 'text', placeholder: 'Si aplica (con SIM)', col: 1 },
    { key: 'storage', label: 'Almacenamiento', type: 'text', placeholder: '64 GB', col: 1 },
    { key: 'ram', label: 'RAM', type: 'text', placeholder: '4 GB', col: 1 },
    { key: 'screenSize', label: 'Tamaño de pantalla', type: 'text', placeholder: '10.9"', col: 1 },
    { key: 'os', label: 'Sistema operativo', type: 'select', options: ['Android', 'iPadOS', 'Windows'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Gris espacial', col: 1 },
    { key: 'hasCharger', label: 'Incluye cargador', type: 'boolean', col: 1 },
    { key: 'hasKeyboard', label: 'Incluye teclado/funda', type: 'boolean', col: 1 },
  ],
  cargador_celular: [
    { key: 'watts', label: 'Potencia (Watts)', type: 'text', placeholder: '20W', col: 1 },
    { key: 'connectorType', label: 'Tipo de conector', type: 'select', options: ['USB-C', 'Lightning', 'Micro-USB', 'USB-A'], col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Blanco', col: 1 },
    { key: 'compatibleBrand', label: 'Marca compatible', type: 'text', placeholder: 'Apple / Samsung / Universal', col: 1 },
  ],
  accesorio: [
    { key: 'accessoryType', label: 'Tipo de accesorio', type: 'text', placeholder: 'Webcam / Audífonos / Hub USB / Dock...', col: 2 },
    { key: 'connectionType', label: 'Tipo de conexión', type: 'text', placeholder: 'USB / Bluetooth / 3.5mm', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
    { key: 'description', label: 'Descripción adicional', type: 'text', placeholder: 'Detalles relevantes', col: 2 },
  ],
  otro: [
    { key: 'description', label: 'Descripción', type: 'text', placeholder: 'Describir el activo', col: 2 },
    { key: 'category', label: 'Categoría', type: 'text', placeholder: 'Mueble / Herramienta / etc.', col: 1 },
    { key: 'color', label: 'Color', type: 'text', placeholder: 'Negro', col: 1 },
  ],
};

export const STATUS_CONFIG = {
  disponible: { label: 'Disponible', color: '#16a34a', bg: '#f0fdf4' },
  asignado: { label: 'Asignado', color: '#d97706', bg: '#fffbeb' },
  baja: { label: 'De baja', color: '#dc2626', bg: '#fef2f2' },
};

export const TYPE_ICONS = {
  laptop: '💻', escritorio: '🖥️', all_in_one: '🖥️',
  monitor: '🖥️', mouse: '🖱️', teclado: '⌨️', cargador_laptop: '🔌',
  celular: '📱', tablet: '📱', cargador_celular: '🔌',
  accesorio: '🎧', otro: '📦',
};
